version: "3.8"
services:

  Exam-Website:
    image: darkghostshade/testy-quest-front-end:latest
    container_name: User-ExamWebsite
    restart: always
    pull_policy: always
    environment: 
    - WATCHPACK_POLLING="true"
    - APICONNECTION=https://Test-Manager-Api:5101
    ports:
    - '3003:3000'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  Test-Manager-Api:
    image: darkghostshade/test-manager-api:latest
    container_name: Test-Manager-Api
    restart: always
    pull_policy: always
    environment: 
    - WATCHPACK_POLLING="true"
    - ASPNETCORE_HTTPS_PORT=5101
    ports:
    - '5101:5000'
    - '8010:80'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5101"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s